package defpackage;

import android.graphics.Bitmap;
import android.graphics.ColorFilter;
import android.graphics.Path;
import android.graphics.PointF;
import android.graphics.Typeface;

/* loaded from: classes.dex */
public interface wc4 {
    public static final Float A;
    public static final Float B;
    public static final Float C;
    public static final Float D;
    public static final Float E;
    public static final Float F;
    public static final Float G;
    public static final Float H;
    public static final Float I;
    public static final Float J;
    public static final ColorFilter K;
    public static final Integer[] L;
    public static final Typeface M;
    public static final Bitmap N;
    public static final CharSequence O;
    public static final Path P;
    public static final Integer a = 1;
    public static final Integer b = 2;
    public static final Integer c = 3;
    public static final Integer d = 4;
    public static final Integer e = 5;
    public static final PointF f = new PointF();
    public static final PointF g = new PointF();
    public static final Float h;
    public static final Float i;
    public static final Float j;
    public static final PointF k;
    public static final PointF l;
    public static final Float m;
    public static final PointF n;
    public static final qa7 o;
    public static final Float p;
    public static final Float q;
    public static final Float r;
    public static final Float s;
    public static final Float t;
    public static final Float u;
    public static final Float v;
    public static final Float w;
    public static final Float x;
    public static final Float y;
    public static final Float z;

    static {
        Float valueOf = Float.valueOf(15.0f);
        h = valueOf;
        Float valueOf2 = Float.valueOf(16.0f);
        i = valueOf2;
        Float valueOf3 = Float.valueOf(17.0f);
        j = valueOf3;
        k = new PointF();
        l = new PointF();
        Float valueOf4 = Float.valueOf(0.0f);
        m = valueOf4;
        n = new PointF();
        o = new qa7();
        p = Float.valueOf(1.0f);
        q = valueOf4;
        r = valueOf4;
        s = Float.valueOf(2.0f);
        t = Float.valueOf(3.0f);
        u = Float.valueOf(4.0f);
        v = Float.valueOf(5.0f);
        w = Float.valueOf(6.0f);
        x = Float.valueOf(7.0f);
        y = Float.valueOf(8.0f);
        z = Float.valueOf(9.0f);
        A = Float.valueOf(10.0f);
        B = Float.valueOf(11.0f);
        C = Float.valueOf(12.0f);
        D = Float.valueOf(12.1f);
        E = Float.valueOf(13.0f);
        F = Float.valueOf(14.0f);
        G = valueOf;
        H = valueOf2;
        I = valueOf3;
        J = Float.valueOf(18.0f);
        K = new ColorFilter();
        L = new Integer[0];
        M = Typeface.DEFAULT;
        N = Bitmap.createBitmap(1, 1, Bitmap.Config.ALPHA_8);
        O = "dynamic_text";
        P = new Path();
    }
}
