package defpackage;

import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* loaded from: classes3.dex */
public abstract class ys9 {
    public static final q8g A;
    public static final q8g B;
    public static final s8g C;
    public static final q8g D;
    public static final s8g E;
    public static final q8g F;
    public static final s8g G;
    public static final q8g H;
    public static final s8g I;
    public static final q8g J;
    public static final s8g K;
    public static final q8g L;
    public static final s8g M;
    public static final q8g N;
    public static final s8g O;
    public static final q8g P;
    public static final s8g Q;
    public static final q8g R;
    public static final s8g S;
    public static final q8g T;
    public static final s8g U;
    public static final q8g V;
    public static final s8g W;
    public static final s8g X;
    public static final q8g a;
    public static final s8g b;
    public static final q8g c;
    public static final s8g d;
    public static final q8g e;
    public static final q8g f;
    public static final s8g g;
    public static final q8g h;
    public static final s8g i;
    public static final q8g j;
    public static final s8g k;
    public static final q8g l;
    public static final s8g m;
    public static final q8g n;
    public static final s8g o;
    public static final q8g p;
    public static final s8g q;
    public static final q8g r;
    public static final s8g s;
    public static final q8g t;
    public static final q8g u;
    public static final q8g v;
    public static final q8g w;
    public static final s8g x;
    public static final q8g y;
    public static final q8g z;

    static {
        q8g c2 = new dr9().c();
        a = c2;
        b = new wr9(Class.class, c2);
        q8g c3 = new ur9().c();
        c = c3;
        d = new wr9(BitSet.class, c3);
        es9 es9Var = new es9();
        e = es9Var;
        f = new gs9();
        g = new yr9(Boolean.TYPE, Boolean.class, es9Var);
        is9 is9Var = new is9();
        h = is9Var;
        i = new yr9(Byte.TYPE, Byte.class, is9Var);
        ks9 ks9Var = new ks9();
        j = ks9Var;
        k = new yr9(Short.TYPE, Short.class, ks9Var);
        ms9 ms9Var = new ms9();
        l = ms9Var;
        m = new yr9(Integer.TYPE, Integer.class, ms9Var);
        q8g c4 = new os9().c();
        n = c4;
        o = new wr9(AtomicInteger.class, c4);
        q8g c5 = new qs9().c();
        p = c5;
        q = new wr9(AtomicBoolean.class, c5);
        q8g c6 = new g9g().c();
        r = c6;
        s = new wr9(AtomicIntegerArray.class, c6);
        t = new i9g();
        u = new k9g();
        v = new m9g();
        o9g o9gVar = new o9g();
        w = o9gVar;
        x = new yr9(Character.TYPE, Character.class, o9gVar);
        q9g q9gVar = new q9g();
        y = q9gVar;
        z = new s9g();
        A = new xq9();
        B = new zq9();
        C = new wr9(String.class, q9gVar);
        br9 br9Var = new br9();
        D = br9Var;
        E = new wr9(StringBuilder.class, br9Var);
        fr9 fr9Var = new fr9();
        F = fr9Var;
        G = new wr9(StringBuffer.class, fr9Var);
        gr9 gr9Var = new gr9();
        H = gr9Var;
        I = new wr9(URL.class, gr9Var);
        hr9 hr9Var = new hr9();
        J = hr9Var;
        K = new wr9(URI.class, hr9Var);
        jr9 jr9Var = new jr9();
        L = jr9Var;
        M = new cs9(InetAddress.class, jr9Var);
        kr9 kr9Var = new kr9();
        N = kr9Var;
        O = new wr9(UUID.class, kr9Var);
        q8g c7 = new lr9().c();
        P = c7;
        Q = new wr9(Currency.class, c7);
        nr9 nr9Var = new nr9();
        R = nr9Var;
        S = new as9(Calendar.class, GregorianCalendar.class, nr9Var);
        or9 or9Var = new or9();
        T = or9Var;
        U = new wr9(Locale.class, or9Var);
        qr9 qr9Var = new qr9();
        V = qr9Var;
        W = new cs9(t7g.class, qr9Var);
        X = new sr9();
    }
}
