package com.android.billingclient.api;

import com.android.billingclient.api.d;

/* loaded from: classes2.dex */
abstract class m {
    static final d A;
    static final d B;
    static final d C;
    static final d a;
    static final d b;
    static final d c;
    static final d d;
    static final d e;
    static final d f;
    static final d g;
    static final d h;
    static final d i;
    static final d j;
    static final d k;
    static final d l;
    static final d m;
    static final d n;
    static final d o;
    static final d p;
    static final d q;
    static final d r;
    static final d s;
    static final d t;
    static final d u;
    static final d v;
    static final d w;
    static final d x;
    static final d y;
    static final d z;

    static {
        d.a c2 = d.c();
        c2.c(3);
        c2.b("Google Play In-app Billing API version is less than 3");
        a = c2.a();
        d.a c3 = d.c();
        c3.c(3);
        c3.b("Google Play In-app Billing API version is less than 9");
        b = c3.a();
        d.a c4 = d.c();
        c4.c(3);
        c4.b("Billing service unavailable on device.");
        c = c4.a();
        d.a c5 = d.c();
        c5.c(5);
        c5.b("Client is already in the process of connecting to billing service.");
        d = c5.a();
        d.a c6 = d.c();
        c6.c(5);
        c6.b("The list of SKUs can't be empty.");
        e = c6.a();
        d.a c7 = d.c();
        c7.c(5);
        c7.b("SKU type can't be empty.");
        f = c7.a();
        d.a c8 = d.c();
        c8.c(5);
        c8.b("Product type can't be empty.");
        g = c8.a();
        d.a c9 = d.c();
        c9.c(-2);
        c9.b("Client does not support extra params.");
        h = c9.a();
        d.a c10 = d.c();
        c10.c(5);
        c10.b("Invalid purchase token.");
        i = c10.a();
        d.a c11 = d.c();
        c11.c(6);
        c11.b("An internal error occurred.");
        j = c11.a();
        d.a c12 = d.c();
        c12.c(5);
        c12.b("SKU can't be null.");
        k = c12.a();
        d.a c13 = d.c();
        c13.c(0);
        l = c13.a();
        d.a c14 = d.c();
        c14.c(-1);
        c14.b("Service connection is disconnected.");
        m = c14.a();
        d.a c15 = d.c();
        c15.c(2);
        c15.b("Timeout communicating with service.");
        n = c15.a();
        d.a c16 = d.c();
        c16.c(-2);
        c16.b("Client does not support subscriptions.");
        o = c16.a();
        d.a c17 = d.c();
        c17.c(-2);
        c17.b("Client does not support subscriptions update.");
        p = c17.a();
        d.a c18 = d.c();
        c18.c(-2);
        c18.b("Client does not support get purchase history.");
        q = c18.a();
        d.a c19 = d.c();
        c19.c(-2);
        c19.b("Client does not support price change confirmation.");
        r = c19.a();
        d.a c20 = d.c();
        c20.c(-2);
        c20.b("Play Store version installed does not support cross selling products.");
        s = c20.a();
        d.a c21 = d.c();
        c21.c(-2);
        c21.b("Client does not support multi-item purchases.");
        t = c21.a();
        d.a c22 = d.c();
        c22.c(-2);
        c22.b("Client does not support offer_id_token.");
        u = c22.a();
        d.a c23 = d.c();
        c23.c(-2);
        c23.b("Client does not support ProductDetails.");
        v = c23.a();
        d.a c24 = d.c();
        c24.c(-2);
        c24.b("Client does not support in-app messages.");
        w = c24.a();
        d.a c25 = d.c();
        c25.c(-2);
        c25.b("Client does not support alternative billing.");
        x = c25.a();
        d.a c26 = d.c();
        c26.c(5);
        c26.b("Unknown feature");
        y = c26.a();
        d.a c27 = d.c();
        c27.c(-2);
        c27.b("Play Store version installed does not support get billing config.");
        z = c27.a();
        d.a c28 = d.c();
        c28.c(-2);
        c28.b("Query product details with serialized docid is not supported.");
        A = c28.a();
        d.a c29 = d.c();
        c29.c(4);
        c29.b("Item is unavailable for purchase.");
        B = c29.a();
        d.a c30 = d.c();
        c30.c(-2);
        c30.b("Query product details with developer specified account is not supported.");
        C = c30.a();
    }

    static d a(int i2, String str) {
        d.a c2 = d.c();
        c2.c(i2);
        c2.b(str);
        return c2.a();
    }
}
